name: plot
channels:
  - conda-forge
dependencies:
    - python=3.8
    - pip>=19.0
    - jupyter
    - scikit-learn
    - scipy
    - pandas
    - matplotlib
    - seaborn
    - ipykernel
    - tslearn

        
